# Default values for helm-schema-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
Image: "confluentinc/cp-schema-registry:3.2.0@sha256:ae0a2021a7ac52bdb98dd760850a50d72747a62612f257be92b0698654bac70d"
Port: "8081"
